# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Telegram\Bot\Skeleton\Application\Converter\TelegramParametersConverter:
        class: Telegram\Bot\Skeleton\Application\Converter\TelegramParametersConverter
        arguments: ['Telegram\Bot\Skeleton\Domain\Factory\UserFactory']
        tags:
            - { name: "telegramParametersConverter", priority: -1, converter: TelegramParametersConverter }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Telegram\Bot\Skeleton\Application\:
        resource: '../src/Application/*'
    Telegram\Bot\Skeleton\Domain\:
        resource: '../src/Domain/*'
    Telegram\Bot\Skeleton\Infrastructure\:
        resource: '../src/Infrastructure/*'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Telegram\Bot\Skeleton\Application\Controller\:
        resource: '../src/Application/Controller'
        tags: ['controller.service_arguments']
    Telegram\Bot\Skeleton\Application\Validator\UserValidatorInterface:
        class: Telegram\Bot\Skeleton\Application\Validator\UserValidator
    Telegram\Bot\Skeleton\Domain\Factory\UserFactory:
        arguments:
          - '@Telegram\Bot\Skeleton\Application\Validator\UserValidatorInterface'

    Illuminate.Database.Capsule.Manager:
        class: Illuminate\Database\Capsule\Manager
        public: false
    Telegram\Bot\Skeleton\Infrastructure\DatabaseConnector:
        arguments: ['@Illuminate.Database.Capsule.Manager']
        public: true
